name: Ci

on: 
  push:
    branches:
    - HW1


env: 
  BUILD_TYPE: Release


jobs:

  cppcheck-test:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          ref: HW1
          
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          
          
          
  tests:
    needs: [cppcheck-test]
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v3
      with:
        ref: HW1
        
    - name: submodule Gtest
      run: git submodule update --init --recursive
        
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}