name: Ci

on: 
  push:
    branches:
    - HW1


env: 
  BUILD_TYPE: Release


jobs:

  cppcheck-test:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}